"""Deterministic original C artifacts and exclusive, explicitly incomplete writes."""
from __future__ import annotations
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import platform
import numpy as np
import scipy
from .spec import BiquadForgeError
from .qualification import BuildResult

SCHEDULES = [1, 3, 7, 16, 127, "whole_vector", [1, 7, 4, 31, 64]]
LIMITATIONS = ["Finite grid and named finite vectors only; no whole-band or arbitrary-input guarantee.",
              "No claim of limit-cycle freedom; quiet final output does not imply quiet internal state.",
              "Standard scalar postShift 0..3 only; fast/DSP/Neon/MVE paths unverified.",
              "No Arm hardware, firmware, real-time, ABI-portability or safety-critical validation."]


def canonical_json(value):
    return (json.dumps(value, sort_keys=True, indent=2, allow_nan=False) + "\n").encode("utf-8")


def _array(values):
    return ",".join(str(int(v)) for v in values)


def render_c(name, coefficients, post_shift, vectors):
    """Pure renderer; verifier validates all arguments before using this function."""
    prefix = "bqf_" + name
    n = len(coefficients)
    flat = [v for row in coefficients for v in row]
    header = f'''/* Generated by BiquadForge. Finite-suite scalar Q15 evidence only. */
#ifndef {prefix.upper()}_H
#define {prefix.upper()}_H
#include "dsp/filtering_functions.h"
#ifdef __cplusplus
extern "C" {{
#endif
#define {prefix.upper()}_STAGES {n}
#define {prefix.upper()}_POST_SHIFT {post_shift}
extern const q15_t {prefix}_coefficients[{6*n}];
typedef struct {{
    arm_biquad_casd_df1_inst_q15 instance;
    q15_t state[{4*n}];
}} {prefix}_context;
/* Each context owns its state. Initialize before use; reset only explicitly.
 * Q15 integer input/output: no hidden attenuation or float conversion.
 * Evidence covers standard scalar CMSIS only, not fast or vector variants. */
void {prefix}_init({prefix}_context *context);
void {prefix}_reset({prefix}_context *context);
void {prefix}_process({prefix}_context *context, const q15_t *input,
                     q15_t *output, uint32_t count);
#ifdef __cplusplus
}}
#endif
#endif
'''
    source = f'''/* Generated original integration; CMSIS source is supplied separately. */
#include "filter.h"
const q15_t {prefix}_coefficients[{6*n}] = {{{_array(flat)}}};
void {prefix}_init({prefix}_context *context) {{
    arm_biquad_cascade_df1_init_q15(&context->instance, {n},
        {prefix}_coefficients, context->state, {post_shift});
}}
void {prefix}_reset({prefix}_context *context) {{ {prefix}_init(context); }}
void {prefix}_process({prefix}_context *context, const q15_t *input,
                     q15_t *output, uint32_t count) {{
    if (count) arm_biquad_cascade_df1_q15(&context->instance, input, output, count);
}}
'''
    arrays = ["/* Exact generated integer replay vectors; no PRNG at replay time. */\n#include \"filter.h\"\n"]
    rows = []
    for i,v in enumerate(vectors):
        for suffix,data in (("in",v["input"]),("out",v["output"]),("state",[x for row in v["final_state"] for x in row])):
            arrays.append(f"static const q15_t test_{i}_{suffix}[] = {{{_array(data)}}};\n")
        rows.append(f"{{test_{i}_in,test_{i}_out,test_{i}_state,{len(v['input'])}}}")
    arrays.append("typedef struct { const q15_t *input, *output, *state; uint32_t length; } test_vector;\n")
    arrays.append("static const test_vector vectors[] = {"+",".join(rows)+"};\n")
    replay = f'''/* Host scalar regression. Outputs AND final state checked per schedule. */
#include <stdio.h>
#include <stdlib.h>
#include "filter.h"
#include "vectors.h"
int main(void) {{
    const unsigned chunks[7] = {{1,3,7,16,127,0,0}};
    const unsigned cycle[5] = {{1,7,4,31,64}};
    unsigned long checked = 0;
    for (unsigned v = 0; v < sizeof(vectors)/sizeof(vectors[0]); ++v) {{
        const test_vector *test = &vectors[v];
        q15_t *output = (q15_t *)malloc(test->length * sizeof(q15_t));
        if (!output) return 3;
        for (unsigned schedule = 0; schedule < 7; ++schedule) {{
            {prefix}_context context;
            {prefix}_init(&context);
            unsigned step = 0;
            for (uint32_t pos = 0; pos < test->length;) {{
                uint32_t size = schedule == 6 ? cycle[(step++)%5] : chunks[schedule];
                if (!size) size = test->length;
                if (size > test->length-pos) size = test->length-pos;
                {prefix}_process(&context, test->input+pos, output+pos, size);
                pos += size;
            }}
            for (uint32_t i = 0; i < test->length; ++i) {{
                if (output[i] != test->output[i]) {{
                    fprintf(stderr,"output mismatch vector=%u schedule=%u sample=%u\\n",v,schedule,(unsigned)i);
                    free(output); return 1;
                }}
            }}
            for (unsigned i = 0; i < {4*n}; ++i) {{
                if (context.state[i] != test->state[i]) {{
                    fprintf(stderr,"state mismatch vector=%u schedule=%u index=%u\\n",v,schedule,i);
                    free(output); return 2;
                }}
            }}
            checked += test->length;
        }}
        free(output);
    }}
    printf("{{\\"status\\":\\"verified\\",\\"vectors\\":%u,\\"schedules\\":7,\\"sample_comparisons\\":%lu,\\"state_comparisons\\":%u}}\\n",
           (unsigned)(sizeof(vectors)/sizeof(vectors[0])),checked,
           (unsigned)(sizeof(vectors)/sizeof(vectors[0]))*7*{4*n});
    return 0;
}}
'''
    return {"filter.h":header.encode(),"filter.c":source.encode(),"vectors.h":"".join(arrays).encode(),"replay.c":replay.encode()}


def make_manifest(result):
    spec = asdict(result.spec)
    spec["vectors"] = [{k:v for k,v in asdict(x).items() if k != "samples"} for x in result.spec.vectors]
    return {"schema_version":1,"tool":{"name":"biquadforge","version":"0.1.0",
            "python":platform.python_version(),"numpy":np.__version__,"scipy":scipy.__version__},
            "status":result.status,"scope":"accepted candidates are qualified only for this finite suite",
            "limitations":LIMITATIONS,"resolved_spec":spec,"search":result.search,
            "selected":asdict(result.chosen) if result.chosen else None,
            "diagnostics":[asdict(d) for d in result.diagnostics],"diagnostic_tails":list(result.diagnostic_tails),"observations":list(result.observations),
            "quantization":{"coefficient_rounding":"float64 nearest-even; reject out-of-range, no clipping",
                            "runtime":"int64 five-product accumulation; arithmetic shift floor; int16 saturation",
                            "state_order":["x[n-1]","x[n-2]","y[n-1]","y[n-2]"],
                            "coefficient_layout":["b0",0,"b1","b2","-a1","-a2"]},
            "verification":{"status":"not_requested","host_c":"unverified","arm_hardware":"unverified"}}


def render_report(manifest, vectors):
    lines = ["# BiquadForge finite-suite qualification", "", "Status: **"+manifest["status"]+"**", "", "## Prominent observations"]
    lines += ["- "+x for x in manifest["observations"]] or (["- No nonzero stage tail was observed in this finite suite."] if manifest["selected"] else ["- No accepted candidate; see rejection diagnostics below."])
    for v in vectors:
        if v["tail"]["nonzero_tail_stages"]:
            lines.append(f"- {v['name']}: stage tail peaks Q15={v['metrics']['tail_peaks_q15']}; full-state result={v['tail']['cycle']['status']}.")
    lines += ["", "Host C: unverified until an explicit successful verify run. Arm hardware: unverified.", "", "## Search", json.dumps({k:v for k,v in manifest["search"].items() if k not in ("descriptors","early_rejection_examples")},sort_keys=True), "", "## Requirements", json.dumps(manifest["resolved_spec"]["limits"],sort_keys=True), "", "## Scope and limitations"]
    lines += ["- "+v for v in LIMITATIONS]
    if manifest["diagnostics"]:
        lines += ["", "## Rejected diagnostic candidates (not deployment artifacts)"]
        for d in manifest["diagnostics"]:
            lines.append(f"- Candidate {d['ordinal']}: failed {', '.join(d['failures'])}; final-tail peak={d['max_final_tail_q15']} Q15; all-stage tail peak={d['max_internal_tail_q15']} Q15.")
        for d in manifest.get("diagnostic_tails", []):
            for v in d["vectors"]:
                if v["tail"]["nonzero_tail_stages"]:
                    lines.append(f"- Candidate {d['ordinal']}, {v['name']}: stage tail peaks={v['tail_peaks_q15']}; full-state result={v['tail']['cycle']['status']}.")
    lines += ["", "The frequency criterion is sampled complex-response error, not a continuous-band bound.", "No candidate scores are held-out benchmarks; no optimizer-superiority claim is made."]
    return ("\n".join(lines)+"\n").encode()


def render_pack(result):
    manifest = make_manifest(result)
    files = {}
    if result.chosen:
        p=result.chosen.prepared
        files.update(render_c(result.spec.name,p.coefficients,p.descriptor.post_shift,result.replay_vectors))
        files["vectors.json"] = canonical_json({"schema_version":1,"schedules":SCHEDULES,"vectors":result.replay_vectors})
    readme = "# Generated BiquadForge pack\n\n" + ("Use filter.h/filter.c with standard scalar CMSIS-DSP. Each caller-owned context must be initialized.\nCall reset only when deliberately discarding state. Input/output are Q15 integers.\n\nExplicit optional verification: biquadforge verify PACK --cmsis-root PATH\nThe source must match the pinned cmsisdsp Python distribution 1.10.3 fixture.\nA compiler is not required to build this pack. No downloads occur during verification.\n" if result.chosen else "No candidate passed the requested finite qualification within the evaluated search.\nThis diagnostic pack deliberately contains no deployment header or source.\n")
    readme += "\nSee report.md and manifest.json for thresholds, internal residuals and search scope.\nNever use an INCOMPLETE directory. Writes use exclusive reservation and best-effort\ninterruption handling, not universal atomicity or crash durability.\n"
    files["README.md"] = readme.encode()
    manifest["artifact_sha256"] = {k:hashlib.sha256(v).hexdigest() for k,v in sorted(files.items())}
    files["manifest.json"] = canonical_json(manifest)
    files["report.md"] = render_report(manifest,result.replay_vectors)
    return files


def _write_exclusive(path, data):
    with path.open("xb") as f:
        f.write(data)


def write_pack(result: BuildResult, out: str | Path) -> Path:
    out=Path(out)
    try:
        out.mkdir()  # Exclusive even for dangling symlinks or existing empty directories.
    except OSError as e:
        raise BiquadForgeError(f"Cannot reserve new output directory; existing paths are preserved: {e}", "out") from e
    try:
        _write_exclusive(out/"INCOMPLETE",b"Incomplete BiquadForge output. Do not use.\n")
        staging=out/"_staging"; staging.mkdir()
        files=render_pack(result)
        for name,data in sorted(files.items()):
            _write_exclusive(staging/name,data)
        for name in sorted(files):
            _write_exclusive(out/name,(staging/name).read_bytes())
            (staging/name).unlink()
        staging.rmdir()
        (out/"INCOMPLETE").unlink()
    except (OSError,ValueError,TypeError,KeyboardInterrupt) as e:
        raise BiquadForgeError(f"Output remains incomplete at {out}: {e}", "out") from e
    return out
